--- #YAML:1.0
name:               App-PDBRun
version:            0.00_01
abstract:           Run commands with PDB IDs as arguments
author:
    - Miorel-Lucian Palii <mlpalii@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Exporter:             0
    Fcntl:                0
    File::HomeDir:        0
    File::Path:           0
    File::Spec:           0
    File::Temp:           0
    IO::File:             0
    IO::Uncompress::Gunzip:  0
    Net::FTP:             0
    perl:                 5.006
resources:
    repository:  http://elementsofpuzzle.googlecode.com/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
